const actionTypes = {
    SET_MOVIES: 'SET_MOVIES',
    SET_SELECTED_YEAR: 'SET_SELECTED_YEAR',
    SET_SELECTED_GENRES: 'SET_SELECTED_GENRES',
    SET_GENRES: 'SET_GENRES',
    SET_CRITERION: 'SET_CRITERION',
    SET_LIST_VIEW: 'SET_LIST_VIEW',
    SET_MOVIE: 'SET_MOVIE',
    SET_SELECTED_CRITERION: 'SET_SELECTED_CRITERION',
}
export default actionTypes;